const { customer } = require('./db_buildSchema');
module.exports = async () => {
    const allDataCustomer = [
        {
            id:1,
            firstname: 'alaa',
            lastname: 'badra',
            email: 'alaabadra4@gmail.com',
            password: '$2a$05$6Q1VE6DzhS8Z2pBr1VEPv.sM2dWPKacPv9GFC5M1.auGPlbab38aK',
            phoneNumber:282,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        }, {

            id:2,
            firstname: 'ala',
            lastname: 'tare',
            email: 'aa@hotmail.com',
            password: '$2a$05$xuOTwN1iWrraW7Og7cVAWu00RUpEXg6AV8X3Mz8cIUoQcT952FJ7e',
            phoneNumber: 234,
            street:'areha',
            city:'american',
            zipCode:12334,
            ipsid:4566,
        }, {
            id:3,
            firstname: "alaa",
            lastname: 'bad',
            email: 'dim@gmail.com',
            password: '$2a$05$mjKkeAAMAaEsORbu.ZQKQurq4nr3pW3n524uwz9uQBrwLt3iGMAQG',
            phoneNumber: 482,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566
        }, {
            id:4,
            firstname: 'ala',
            lastname: 'tare',
            email:'bbb@hotmail.com',
            password: '$2a$05$rZ6MiHZcvdMzVwTyJsyJf.o.CXVgP0xt72NO0JzPL3o4uYtSfgJ9C',
            phoneNumber:124,
            street:'areha',
            city:'american',
            zipCode:12334,
            ipsid:4566,
        },
        {
            id:5,
            firstname: 'alaa',
            lastname:'badra',
            email: 'algg4@gmail.com',
            password: '$2a$05$NaOMIHK8COoVXp1xikmcauCal6Cx1K.pTqszE8Gw2RbbgbcjWQ0VO',
            phoneNumber:282,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        },
        {
            id:6,
            firstname: 'alaa',
            lastname: 'tare',
            email: 'ajkjl@hotmail.com',
            password: '$2a$05$gjz9fzt2CFQK6Zrhm8vUW.P4fQEz/2K4DfEJvlFGt7Gmb/o1xRg32',
            phoneNumber:154,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        },
        {
            id:7,
            firstname: 'alaa',
            lastname: 'badra',
            email: 'kja4@gmail.com',
            password: '$2a$05$V1KoBQdLmude8L1ZaQbkjux/qcf05Z0/HiPhgdZz7ZZk2Gc4dUa1i',
            phoneNumber:787,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        },
        {
            id:8,
            firstname: 'alaa',
            lastname: 'tare',
            email:'axxxa@hotmmmail.com',
            password: '$2a$05$YatyAOyRB6VRqlWVE3xPY.NvCSMDuMo8V4Dh8/uT8hygqGUVVpKCe',
            phoneNumber:157,
            street:'areha',
            city:'american',
            zipCode:12334,
            ipsid:4566,
        }, {
            id:9,
            firstname: 'alaa',
            lastname: 'badra',
            email: 'afyya4@gmail.com',
            password: ' $2a$05$N8bFcn7dxFTo9T3iyuhg7OmyME9NwNCd6EwSJRA62FPRmnzY1QO/q',
            phoneNumber: 3.2,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        }, {
            id:10,
            firstname: 'ala',
            lastname: 'tare',
            email:'afffa@mail.com',
            password: '$2a$05$dpziTRD44Dy/P1stEJbfuu086NMHE2481zEAVOpyEB3bDAmhySer2',
            phoneNumber: 574,
            street:'areha',
            city:'american',
            zipCode:12334,
            ipsid:4566
        }, {
            id:11,
            firstname: 'alaa',
            lastname: 'badra',
            email: 'snssm4@gmail.com',
            password: '$2a$05$S8/r6KCtDwgvu1un1QgtxuZuNh2IHUm8SY0ZyUsuwapKU3/owa7vS',
            phoneNumber:485,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        }, {
            id:12,
            firstname: 'ala',
            lastname: 'tera',
            email: 'aaaa@il.com',
            password: '$2a$05$h8anTFmZNXG8mK53XPbhW.E54heHCiszhcPqEFBpdYILIqblS2fD2',
            phoneNumber: 124,
            street:'areha',
            city:'american',
            zipCode:12334,
            ipsid:4566

        }, {
            id:13,
            firstname: 'ala',
            lastname: 'badra',
            email: 'sabra4@gmail.com',
            password: '$2a$05$wvkNaf.YNF7ehwEE1qKncurUM9DjbRFLeAXoXLlM72r3y9Bfr1O9m',
            phoneNumber:482,
            street:'salah',
            city:'gaza',
            zipCode:12334,
            ipsid:4566,
        }

    ]

    return customer.create(allDataCustomer)
}
