INSERT INTO admin (
    id,
    name,
    firstname,
    lastname,
    email,
    password,
    phonenumber,
    street,
    city,
    zipcode,
    ipsid,
    username,
    emailnotification,
    passwordtoken,
    list_id
  )
VALUES
(
    4,
    'Shubz',
    'Shubziano',
    'Awo',
    'chopchowsd@gmail.com',
    '$2a$05$781WhkOHmg8aChp1Hnw/NeWTtnTUckGUFcl9fnakAzqXCQTKifNPa',
    8587546183,
    'La Jolla',
    'San Diego',
    92122,
    4566,
    'Shubziano',
    true,
    null,
    1
),
(
    2,
    'Subomi',
    'Olasubomi',
    'Awokoya',
    'olasubomi.awokoya@hotmail.com',
    '$2a$05$C2OPWtVFkyH/WBayaDmAduMiFVeHTenP8Cb8PVeWa8C.sSdKKE2O.',
    8587546183,
    'La Jolla',
    'San Diego',
    92122,
    4566,
    'Subomi',
    true,
    null,
    1
),(
    3,
    'Subomi',
    'Subomi',
    'Awokoya',
    'iamsubomi@gmail.com',
    '$2a$05$6Q1VE6DzhS8Z2pBr1VEPv.sM2dWPKacPv9GFC5M1.auGPlbab38aK',
    8587546183,
    'La Jolla',
    'San Diego',
    92131,
    4566,
    'Subomi',
    true,
    null,
    1
  );
 